#!/usr/bin/env python3
"""Generate the report's tables from the committed contracts.

Each function writes one booktabs fragment that a section pulls in with
`\\input`. The point is the same as for the figures: a number in the manuscript
should not be a number somebody typed. Change a contract, re-run this, and the
table follows.

    python docs/research_report/tables/make_tables.py
    python docs/research_report/tables/make_tables.py --check   # no writes

`--check` regenerates into memory and compares against what is on disk, so the
build can tell you a fragment is stale without rewriting it.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[2]

DATASETS = ("unsw_nb15", "ton_iot")
SHORT = {"unsw_nb15": "UNSW", "ton_iot": "ToN"}


def load(rel: str):
    return json.loads((ROOT / rel).read_text())


def fmt(value: float, places: int = 4, signed: bool = False) -> str:
    return f"{value:+.{places}f}" if signed else f"{value:.{places}f}"


def ci(block: dict) -> str:
    return (
        f"${fmt(block['mean_diff'], signed=True)}$ "
        f"[${fmt(block['ci_low'], signed=True)}$, ${fmt(block['ci_high'], signed=True)}$]"
    )


def wrap(caption: str, label: str, body: str, size: str = "small", resize: bool = True) -> str:
    inner = "\\resizebox{\\textwidth}{!}{%\n" + body + "\n}" if resize else body
    return (
        "% Generated by docs/research_report/tables/make_tables.py. Do not edit by hand.\n"
        "\\begin{table}[htbp]\n\\centering\n"
        f"\\caption{{{caption}}}\n\\label{{{label}}}\n\\{size}\n"
        f"{inner}\n\\end{{table}}\n"
    )


# ---------------------------------------------------------------------------


def table_ladder() -> str:
    head = load("results/multiseed_ladder_v2_head.json")
    proto = load("results/multiseed_ladder_v2_legacy.json")
    rows = []

    def cells(rung: dict) -> str:
        seeds = " / ".join(fmt(rung["per_seed"][s]) for s in ("42", "1", "2"))
        return f"${fmt(rung['mean'])} \\pm {fmt(rung['std'])}$ & {seeds}"

    for label, key, source in (
        ("GNN model", "gnn", head),
        ("Semantic model", "llm", head),
        ("Fusion model", "agaf", head),
    ):
        rows.append(
            f"{label:<30} & " + " & ".join(cells(source[d]["rungs"][key]) for d in DATASETS) + " \\\\"
        )
    rows.append("\\midrule")
    rows.append(
        "Feedback model, prototype consultant    & "
        + " & ".join(cells(proto[d]["rungs"]["loop"]) for d in DATASETS)
        + " \\\\"
    )
    rows.append(
        "Feedback model, trained-head consultant & "
        + " & ".join(cells(head[d]["rungs"]["loop"]) for d in DATASETS)
        + " \\\\"
    )
    body = (
        "\\begin{tabular}{lcccc}\n\\toprule\n"
        "& \\multicolumn{2}{c}{NF-UNSW-NB15 (10 classes)} & \\multicolumn{2}{c}{NF-ToN-IoT (8 classes)} \\\\\n"
        "\\cmidrule(lr){2-3}\\cmidrule(lr){4-5}\n"
        "Rung & mean $\\pm$ std & seeds 42 / 1 / 2 & mean $\\pm$ std & seeds 42 / 1 / 2 \\\\\n"
        "\\midrule\n" + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}"
    )
    return wrap(
        "Pooled out-of-fold macro-F1 by rung, three training seeds at a fixed fold partition. "
        "The feedback model is reported under both consultants. The $\\pm$ is training-seed variance only. "
        "Absolute levels are not comparable across datasets.",
        "tab:ladder",
        body,
    )


def table_comparisons() -> str:
    head = load("results/multiseed_ladder_v2_head.json")
    proto = load("results/multiseed_ladder_v2_legacy.json")
    plan = {
        "unsw_nb15": [
            ("feedback $-$ fusion", proto, "loop_vs_agaf", "prototype"),
            ("feedback $-$ fusion", head, "loop_vs_agaf", "trained head"),
            ("feedback $-$ GNN", proto, "loop_vs_gnn", "prototype"),
            ("feedback $-$ GNN", head, "loop_vs_gnn", "trained head"),
            ("feedback $-$ semantic", proto, "loop_vs_llm", "prototype"),
            ("feedback $-$ semantic", head, "loop_vs_llm", "trained head"),
            ("fusion $-$ GNN", head, "agaf_vs_gnn", "either"),
        ],
        "ton_iot": [
            ("feedback $-$ fusion", proto, "loop_vs_agaf", "prototype"),
            ("feedback $-$ fusion", head, "loop_vs_agaf", "trained head"),
            ("feedback $-$ GNN", proto, "loop_vs_gnn", "prototype"),
            ("feedback $-$ GNN", head, "loop_vs_gnn", "trained head"),
            ("feedback $-$ semantic", proto, "loop_vs_llm", "prototype"),
            ("feedback $-$ semantic", head, "loop_vs_llm", "trained head"),
            ("fusion $-$ GNN", head, "agaf_vs_gnn", "either"),
        ],
    }
    lines = []
    for i, key in enumerate(DATASETS):
        if i:
            lines.append("\\midrule")
        rows = plan[key]
        lines.append(f"\\multirow{{{len(rows)}}}{{*}}{{{SHORT[key]}}}")
        for label, source, field, consultant in rows:
            comp = source[key]["comparisons"][field]
            two, matched = comp["two_level"], comp["seed_matched"]
            sep = "yes" if (two["ci_low"] > 0 or two["ci_high"] < 0) else "no"
            stable = "yes" if comp["sign_stable_across_seeds"] else "no"
            lines.append(
                f" & {label:<18} & {consultant:<12} & {ci(two)} & {sep:<3} & {ci(matched)} & {stable} \\\\"
            )
    body = (
        "\\begin{tabular}{lllcccc}\n\\toprule\n"
        "Dataset & Comparison & Consultant & two-level mean [95\\% CI] & sep "
        "& seed-matched mean [95\\% CI] & stable \\\\\n\\midrule\n"
        + "\n".join(lines)
        + "\n\\bottomrule\n\\end{tabular}"
    )
    return wrap(
        "Rung comparisons, both bootstrap procedures, 2{,}000 iterations. \\emph{Sep} marks an "
        "interval that excludes zero. \\emph{Stable} reports whether the sign of the per-seed "
        "difference is the same at all three seeds. Each comparison is given at both "
        "consultants, so a row's verdict can be read against the consultant that produced "
        "it.",
        "tab:comparisons",
        body,
        size="footnotesize",
    )


def table_metrics() -> str:
    """Macro-F1 beside accuracy and weighted F1, on the rows the metric scores.

    The instructor's brief asks for accuracy. It is reported here rather than in
    the headline table because on NF-ToN-IoT it barely separates the rungs: the
    benign class holds 82% of the scored edges, so a rung can be well above
    another on macro-F1 and a point or two away on accuracy.
    """
    head = load("results/multiseed_ladder_v2_head.json")
    proto = load("results/multiseed_ladder_v2_legacy.json")

    def cells(rung: dict) -> str:
        parts = []
        for key in ("macro_f1", "accuracy", "weighted_f1"):
            block = rung if key == "macro_f1" else rung[key]
            mean = block["mean"] if key == "macro_f1" else block["mean"]
            std = block["std"] if key == "macro_f1" else block["std"]
            parts.append(f"${fmt(mean)} \\pm {fmt(std)}$")
        return " & ".join(parts)

    rows = []
    for label, key, source in (
        ("GNN model", "gnn", head),
        ("Semantic model", "llm", head),
        ("Fusion model", "agaf", head),
    ):
        rows.append(
            f"{label:<38} & "
            + " & ".join(cells(source[d]["rungs"][key]) for d in DATASETS)
            + " \\\\"
        )
    rows.append("\\midrule")
    rows.append(
        "Feedback model, prototype consultant    & "
        + " & ".join(cells(proto[d]["rungs"]["loop"]) for d in DATASETS)
        + " \\\\"
    )
    rows.append(
        "Feedback model, trained-head consultant & "
        + " & ".join(cells(head[d]["rungs"]["loop"]) for d in DATASETS)
        + " \\\\"
    )
    body = (
        "\\begin{tabular}{lcccccc}\n\\toprule\n"
        "& \\multicolumn{3}{c}{NF-UNSW-NB15 (10 classes)} "
        "& \\multicolumn{3}{c}{NF-ToN-IoT (8 classes)} \\\\\n"
        "\\cmidrule(lr){2-4}\\cmidrule(lr){5-7}\n"
        "Rung & macro-F1 & accuracy & weighted F1 & macro-F1 & accuracy & weighted F1 \\\\\n"
        "\\midrule\n" + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}"
    )
    return wrap(
        "Three metrics per rung, mean $\\pm$ training-seed standard deviation over three seeds, "
        "all scored on the rows the metric scores. Accuracy on NF-ToN-IoT is dominated by the "
        "benign class, which holds 82\\% of those edges, so every graph rung sits above 0.83 "
        "there and the metric separates them far less than macro-F1 does. Macro-F1 weights a "
        "12-edge class the same as a 1{,}746-edge one, which is why it is the headline.",
        "tab:metrics",
        body,
    )


def table_ablations() -> str:
    lines = []
    for i, key in enumerate(DATASETS):
        if i:
            lines.append("\\midrule")
        per_seed = load(f"results/{key}_current.json")["feedback_ablations_per_seed"]
        lines.append(f"\\multirow{{3}}{{*}}{{{SHORT[key]}}}")
        for seed in ("42", "1", "2"):
            row = per_seed[seed]
            lines.append(
                f" & {seed:<3} & {fmt(row['real'])} & {fmt(row['head_only'])} "
                f"& {fmt(row['random'])} & {ci(row['real_vs_head_only'])} \\\\"
            )
    body = (
        "\\begin{tabular}{llcccc}\n\\toprule\n"
        "Dataset & Seed & real & \\texttt{head\\_only} & random "
        "& real $-$ \\texttt{head\\_only} [95\\% CI] \\\\\n\\midrule\n"
        + "\n".join(lines)
        + "\n\\bottomrule\n\\end{tabular}"
    )
    return wrap(
        "Feedback ablation, per training seed, fusion active in all arms. The interval is a "
        "paired bootstrap of real against \\texttt{head\\_only}.",
        "tab:ablations",
        body,
    )


def table_mechanism() -> str:
    data = {k: load(f"results/{k}_oracle_ceiling_v2_trained_head.json") for k in DATASETS}
    arms = [
        ("control (\\texttt{head\\_only})", "control_head_only", None),
        ("prototype, edge", "real_prototype_edge", "real_prototype_edge_vs_control_head_only"),
        ("trained head, edge", "head_trained_edge", "head_trained_edge_vs_control_head_only"),
        ("oracle, edge", "oracle_edge", "oracle_edge_vs_control_head_only"),
        ("oracle, attention", "oracle_attention", "oracle_attention_vs_control_head_only"),
    ]
    lines = []
    for label, arm, field in arms:
        cells = []
        for key in DATASETS:
            mean = fmt(data[key]["results"][arm]["mean"])
            paired = ci(data[key]["paired_comparisons"][field]) if field else "--"
            cells += [mean, paired]
        lines.append(f"{label:<30} & " + " & ".join(cells) + " \\\\")
    lines.append("\\midrule")
    lines.append("\\multicolumn{5}{l}{\\emph{Pooled headroom and captured share}} \\\\")
    dec = {k: data[k]["decision"] for k in DATASETS}
    for label, field, pct in (
        ("oracle headroom", "oracle_edge_headroom", False),
        ("prototype share", "prototype_captured_share", True),
        ("trained head share", "trained_head_captured_share", True),
    ):
        cells = []
        for key in DATASETS:
            value = dec[key][field]
            cells.append(
                f"\\multicolumn{{2}}{{c}}{{${100 * value:+.1f}\\%$}}"
                if pct
                else f"\\multicolumn{{2}}{{c}}{{${fmt(value, signed=True)}$}}"
            )
        lines.append(f"{label:<30} & " + " & ".join(cells) + " \\\\")
    body = (
        "\\begin{tabular}{lcccc}\n\\toprule\n"
        "& \\multicolumn{2}{c}{NF-UNSW-NB15} & \\multicolumn{2}{c}{NF-ToN-IoT} \\\\\n"
        "\\cmidrule(lr){2-3}\\cmidrule(lr){4-5}\n"
        "Arm & mean & paired diff vs control [95\\% CI] & mean "
        "& paired diff vs control [95\\% CI] \\\\\n\\midrule\n"
        + "\n".join(lines)
        + "\n\\bottomrule\n\\end{tabular}"
    )
    return wrap(
        "Mechanism in isolation, output fusion disabled in every arm. Means are over three "
        "seeds; intervals are paired over the fifteen (seed, fold) pairs. Captured share is the "
        "arm's gain as a fraction of the oracle's.",
        "tab:mechanism",
        body,
        size="footnotesize",
    )


def table_baselines() -> str:
    data = {k: load(f"results/{k}_sota_baselines.json")["baselines"] for k in DATASETS}
    arch_names = {"e_graphsage": "E-GraphSAGE", "te_g_sage": "TE-G-SAGE"}
    cfg_names = {
        "as_published": ("as published", "yes"),
        "refit": ("refit", "yes"),
        "plus_node_features": ("$+$ our node features", "no"),
    }
    lines = []
    for i, arch in enumerate(("e_graphsage", "te_g_sage")):
        if i:
            lines.append("\\midrule")
        lines.append(f"\\multirow{{3}}{{*}}{{{arch_names[arch]}}}")
        for cfg, (cfg_label, faithful) in cfg_names.items():
            cells = []
            for key in DATASETS:
                block = data[key][arch][cfg]
                cells.append(f"${fmt(block['macro_f1'])} \\pm {fmt(block['macro_f1_std'])}$")
            lines.append(f" & {cfg_label:<22} & {faithful:<3} & " + " & ".join(cells) + " \\\\")
    body = (
        "\\begin{tabular}{lllcc}\n\\toprule\n"
        "Architecture & Configuration & Faithful & NF-UNSW-NB15 & NF-ToN-IoT \\\\\n\\midrule\n"
        + "\n".join(lines)
        + "\n\\bottomrule\n\\end{tabular}"
    )
    return wrap(
        "Re-trained baselines, mean pooled out-of-fold macro-F1 over seeds 42, 1 and 2. "
        "\\emph{Faithful} marks a configuration that is the published architecture; "
        "\\texttt{+ node features} is a labelled ablation of ours and must not be tabulated "
        "under the paper's name.",
        "tab:baselines",
        body,
    )


def table_vsbaselines() -> str:
    order = [
        ("e_graphsage_as_published", "E-GraphSAGE, as published"),
        ("e_graphsage_refit", "E-GraphSAGE, refit"),
        ("e_graphsage_plus_node_features", "E-GraphSAGE $+$ features"),
        ("te_g_sage_as_published", "TE-G-SAGE, as published"),
        ("te_g_sage_refit", "TE-G-SAGE, refit"),
        ("te_g_sage_plus_node_features", "TE-G-SAGE $+$ features"),
    ]
    lines = []
    for i, key in enumerate(DATASETS):
        if i:
            lines.append("\\midrule")
        contract = load(f"results/{key}_sota_baselines.json")
        head = contract["statistical_comparisons_3seed"]
        proto = contract["superseded"]["whitened_prototype_scorer_3seed"][
            "statistical_comparisons_3seed"
        ]
        lines.append(f"\\multirow{{{len(order)}}}{{*}}{{{SHORT[key]}}}")
        for field, label in order:
            cells = []
            for source in (proto, head):
                comp = source[f"feedback_vs_{field}"]
                text = ci(comp)
                if not (comp["ci_low"] > 0 or comp["ci_high"] < 0):
                    text += " \\emph{ns}"
                cells.append(text)
            lines.append(f" & {label:<26} & " + " & ".join(cells) + " \\\\")
    body = (
        "\\begin{tabular}{llll}\n\\toprule\n"
        "Dataset & Baseline & Feedback model, prototype & Feedback model, trained head \\\\\n"
        "\\midrule\n" + "\n".join(lines) + "\n\\bottomrule\n\\end{tabular}"
    )
    return wrap(
        "The feedback model against each re-trained baseline, under both consultants, two-level bootstrap "
        "over edges and both seed sets. Positive favours our rung. \\emph{ns} marks an interval "
        "containing zero.",
        "tab:vsbaselines",
        body,
        size="footnotesize",
    )


def table_decomposition() -> str:
    d = load("docs/research_report/derived_numbers.json")["decomposition_unsw"]
    levels, ep, agaf_ep = d["levels"], d["endpoint_loop"], d["endpoint_agaf"]
    rows = [
        ("TE-G-SAGE as published", levels["te_g_sage_as_published"], "--", "--"),
        (
            "$+$ fair tuning (refit)",
            levels["te_g_sage_refit"],
            f"${fmt(d['step_tuning'], signed=True)}$, graph scale and schedule",
            f"{ep['share_tuning_percent']}\\%",
        ),
        (
            "$+$ our ten centralities",
            levels["te_g_sage_plus_node_features"],
            f"${fmt(d['step_node_features'], signed=True)}$, feature engineering",
            f"{ep['share_node_features_percent']}\\%",
        ),
        (
            "our feedback model rung",
            levels["loop"],
            f"${fmt(ep['step_architecture'], signed=True)}$, architecture",
            f"{ep['share_architecture_percent']}\\%",
        ),
    ]
    lines = [f"{a:<28} & {fmt(b)} & {c} & {e} \\\\" for a, b, c, e in rows]
    lines.append("\\midrule")
    lines.append(
        f"(our fusion model rung)     & {fmt(levels['agaf'])} & "
        f"${fmt(agaf_ep['step_architecture'], signed=True)}$ over the same base & "
        f"{agaf_ep['share_architecture_percent']}\\% of {fmt(agaf_ep['total_gap'])} \\\\"
    )
    body = (
        "\\begin{tabular}{llcc}\n\\toprule\n"
        "Step & macro-F1 & attributable to & share \\\\\n\\midrule\n"
        + "\n".join(lines)
        + "\n\\bottomrule\n\\end{tabular}"
    )
    return wrap(
        "Decomposition of the NF-UNSW-NB15 gap against TE-G-SAGE. Point estimates only. "
        "Shares are of the total gap to the feedback model, except the final row, "
        "whose share is of the smaller gap to the fusion model and names its own denominator.",
        "tab:decomposition",
        body,
    )


def table_perclass() -> str:
    sys.path.insert(0, str(ROOT))
    from src.pipeline.common.datasets import DATASETS as CFG

    per_class = load("results/multiseed_head_per_class.json")
    stats = load("docs/research_report/dataset_stats.json")
    lines = []
    for key in DATASETS:
        cfg = CFG[key]
        block = per_class[key]["per_class_f1_3seed"]
        counts = stats[key]["class_counts"]
        display = {"unsw_nb15": "NF-UNSW-NB15", "ton_iot": "NF-ToN-IoT"}[key]
        if lines:
            lines.append("\\midrule")
        lines.append(f"\\multicolumn{{5}}{{l}}{{\\emph{{{display}}}}} \\\\")
        for j, ci_ in enumerate(per_class[key]["eval_classes"]):
            name = cfg.label_names[ci_]
            tex = name.replace("_", "\\_")
            if name[0].islower():
                tex = f"\\texttt{{{tex}}}"
            values = " & ".join(fmt(block[r]["mean"][j]) for r in ("gnn", "agaf", "loop"))
            lines.append(f"{tex:<24} & {counts[name]:>4} & {values} \\\\")
    body = (
        "\\begin{tabular}{lrccc}\n\\toprule\n"
        "Class & edges & GNN & fusion & feedback \\\\\n\\midrule\n"
        + "\n".join(lines)
        + "\n\\bottomrule\n\\end{tabular}"
    )
    return wrap(
        "Per-class F1, mean over three seeds, with edge counts. The feedback model is the canonical one, "
        "consulting the trained head. NF-ToN-IoT's \\texttt{dos} and \\texttt{ransomware} are "
        "excluded from the metric and omitted here, and F1 is computed on the rows the metric "
        "scores, so each column's mean is that rung's macro-F1 in Table~\\ref{tab:ladder}.",
        "tab:perclass",
        body,
    )


def table_knobcurves() -> str:
    curves = load("docs/research_report/derived_numbers.json")["knob_curves"]
    lines = []
    for key in DATASETS:
        display = {"unsw_nb15": "NF-UNSW-NB15", "ton_iot": "NF-ToN-IoT"}[key]
        for knob, label in (("top_k", "$k$ (entropy percentile)"), ("scale", "injection scale")):
            c = curves[key][knob]
            boundary = "yes" if c["argmax_on_range_boundary"] else "no"
            lines.append(
                f"{display} & {label} & {c['n_candidates']} & "
                f"{c['candidate_min']:g}--{c['candidate_max']:g} & "
                f"{fmt(c['validation_min'])}--{fmt(c['validation_max'])} & "
                f"{fmt(c['span'])} & {c['argmax_candidate']:g} & {boundary} \\\\"
            )
    body = (
        "\\begin{tabular}{llccccccc}\n\\toprule\n"
        "Dataset & Knob & candidates & range & validation macro-F1 & span & selected "
        "& on boundary \\\\\n\\midrule\n" + "\n".join(lines) + "\n\\bottomrule\n\\end{tabular}"
    )
    return wrap(
        "Knob selection curves for the trained-head consultant, mean validation macro-F1 over "
        "selection seeds 42, 1 and 2. Every span is smaller than the rungs' own seed-to-seed "
        "spread, so the argmax is not distinguishable from its neighbours.",
        "tab:knobcurves",
        body,
        size="footnotesize",
    )


TABLES = {
    "ladder": table_ladder,
    "metrics": table_metrics,
    "comparisons": table_comparisons,
    "ablations": table_ablations,
    "mechanism": table_mechanism,
    "baselines": table_baselines,
    "vsbaselines": table_vsbaselines,
    "decomposition": table_decomposition,
    "perclass": table_perclass,
    "knobcurves": table_knobcurves,
}


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true", help="compare against disk, write nothing")
    args = ap.parse_args()

    stale = []
    for name, builder in TABLES.items():
        text = builder()
        path = HERE / f"tab_{name}.tex"
        if args.check:
            if not path.exists() or path.read_text() != text:
                stale.append(path.name)
        else:
            path.write_text(text)
            print(f"  -> {path.relative_to(ROOT)}")
    if args.check:
        if stale:
            print("stale table fragments: " + ", ".join(stale))
            return 1
        print(f"all {len(TABLES)} table fragments are current")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
